stages:
  - test
  - push image
  - deploy

variables:
  DOCKER_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

test-job:
  stage: test
  tags:
    - build
  script:
    - docker build -t test .
    - docker rmi test

push-docker-job:
  stage: push image
  tags:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
    - if: $CI_COMMIT_BRANCH == "stage"
      when: always
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_TAG .
    - docker push $DOCKER_TAG

deploy-job:
  stage: deploy
  tags:
    - build
  environment:
    name: $CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
    - if: $CI_COMMIT_BRANCH == "stage"
      when: always
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f docker-compose-ci.yaml up -d
