# Stage 1: Build Angular App
FROM node:20-alpine AS builder
WORKDIR /app
COPY . /app
RUN yarn install
RUN yarn build --configuration=production

# Stage 2: Serve Angular App using Nginx
FROM nginx:alpine
COPY --from=builder /app/dist/imis-front /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf 
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]