# Stage 1: Build Angular App
FROM node:20-alpine
WORKDIR /app
COPY . /app
RUN yarn install
RUN yarn build --prod

# Stage 2: Serve Angular App using Nginx
FROM nginx:alpine
COPY --from=build /app/dist/imis-front /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]