version: '3'
services:

  app:
    image: $DOCKER_TAG
    build:
      dockerfile: ./Dockerfile.build
    container_name: SH-b-site-$CI_COMMIT_BRANCH
    restart: always
    ports:
      - "7000:80"
    command: nginx -g "daemon off;"